"""
app/api/schemas.py
------------------
Pydantic v2 request/response models for the Colombian Labor Law RAG API.
These models define the contract between this backend and the React frontend.

Changing field names here is a BREAKING CHANGE for the frontend — coordinate before
modifying.
"""

from __future__ import annotations

from pydantic import BaseModel, Field, field_validator

# ============================================================== Request models


class ChatRequest(BaseModel):
    """Body for POST /chat."""

    question: str = Field(
        ...,
        max_length=2_000,
        description="User question in Spanish about Colombian labor law.",
        examples=["¿Cuántos días de vacaciones tiene un trabajador en Colombia?"],
    )
    conversation_id: str | None = Field(
        default=None,
        description=(
            "Optional ID to group turns into a conversation. "
            # TODO (milestone 3): wire to LangGraph memory / checkpointing.
            "Currently ignored — conversation memory is not yet implemented."
        ),
    )
    max_citations: int | None = Field(
        default=None,
        ge=1,
        le=20,
        description="Maximum number of citations to return. Defaults to server setting.",
    )

    @field_validator("question")
    @classmethod
    def question_must_not_be_blank(cls, v: str) -> str:
        if not v.strip():
            raise ValueError(
                "La pregunta no puede estar vacía. "
                "Por favor escribe una pregunta sobre derecho laboral colombiano."
            )
        return v.strip()


# ============================================================= Response models


class Citation(BaseModel):
    """A single retrieved chunk that supports the generated answer."""

    source: str = Field(
        ...,
        description="File name or URL of the source document.",
        examples=["CST_codigo_sustantivo_trabajo.pdf"],
    )
    page: int | None = Field(
        default=None,
        description="Page number within the source document, if applicable.",
    )
    chunk_id: str | None = Field(
        default=None,
        description="Internal chunk identifier in the vector store.",
    )
    snippet: str = Field(
        ...,
        description="Verbatim or near-verbatim text excerpt from the source.",
    )


class QueryTransformTrace(BaseModel):
    """Traceability record for the adaptive query transformation step."""

    original_query: str = Field(
        ...,
        description="The original user query before any transformation.",
    )
    strategy: str = Field(
        ...,
        description="Strategy applied: 'direct', 'hyde', or 'decomposition'.",
    )
    strategy_reason: str = Field(
        ...,
        description="One or two sentences explaining why this strategy was selected.",
    )
    effective_queries: list[str] = Field(
        default_factory=list,
        description=(
            "The actual queries used for retrieval. "
            "One item for DIRECT/HyDE; multiple items for DECOMPOSITION."
        ),
    )
    hypothetical_document: str | None = Field(
        default=None,
        description="Hypothetical document generated by HyDE; None for other strategies.",
    )


class Trace(BaseModel):
    """Minimal execution trace for debugging and explainability."""

    intent: str | None = Field(
        default=None,
        description="Classified intent of the question (e.g. 'domainSearch', 'summarize', 'compare').",
    )
    top_k: int | None = Field(
        default=None,
        description="Number of chunks retrieved from the vector store.",
    )
    vector_db: str = Field(
        ...,
        description="Vector database backend used for retrieval.",
    )
    llm_provider: str = Field(
        ...,
        description="LLM provider used for answer generation.",
    )
    query_transform: QueryTransformTrace | None = Field(
        default=None,
        description="Query transformation metadata for retrieval traceability.",
    )


class ToolTraceStep(BaseModel):
    """Execution trace for a single Tool invocation."""

    tool_name: str = Field(
        ..., description="Name of the Tool executed (e.g., 'classify_intent', 'semantic_search')."
    )
    status: str = Field(
        default="success", description="Execution status: 'success', 'failure', 'skipped'."
    )
    input: dict | None = Field(default=None, description="Input parameters passed to the Tool.")
    output: dict | None = Field(default=None, description="Output returned by the Tool.")
    error: str | None = Field(default=None, description="Error message if Tool execution failed.")
    timestamp: str | None = Field(default=None, description="ISO timestamp of Tool execution.")


class WorkflowTrace(BaseModel):
    """Complete workflow execution trace with all Tool steps."""

    conversation_id: str = Field(..., description="Conversation ID for session tracking.")
    total_steps: int = Field(default=0, description="Total number of nodes/tools executed.")
    tools_used: list[str] = Field(
        default_factory=list, description="List of Tools called during workflow."
    )
    tool_traces: list[ToolTraceStep] = Field(
        default_factory=list, description="Detailed trace for each Tool invocation."
    )
    validation_passed: bool = Field(
        default=True, description="Whether final answer passed validation."
    )
    validation_details: dict | None = Field(
        default=None, description="Detailed validation scores and reasons."
    )
    execution_time_ms: float | None = Field(
        default=None, description="Total workflow execution time in milliseconds."
    )


class ChatResponse(BaseModel):
    """Full response returned by POST /chat."""

    ok: bool = Field(..., description="Whether the request was processed successfully.")
    request_id: str = Field(
        ...,
        description="Unique UUID for this request, useful for tracing logs.",
    )
    answer: str = Field(
        ...,
        description=(
            "Generated answer in Spanish. "
            "If the information is not in the corpus, equals 'No aparece en el contexto.'"
        ),
    )
    citations: list[Citation] = Field(
        default_factory=list,
        description=(
            "Source chunks that support the answer. "
            "Empty when the answer is 'No aparece en el contexto.'."
        ),
    )
    trace: Trace = Field(
        ...,
        description="Execution trace for debugging.",
    )
    workflow_trace: WorkflowTrace | None = Field(
        default=None,
        description="Complete workflow trace with all Tool steps and validation details.",
    )
    metadata: dict | None = Field(
        default=None,
        description="Additional metadata including tool traces and validation scores.",
    )
